name: PHP CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon.dist
  
  tests:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          configuration: tests/phpunit.xml
          args: --coverage-text

  deploy_dev:
    needs: [lint, tests]
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest    
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v2
      
      # Add private key to ssh agent
      - run: mkdir ~/.ssh; chmod 700 ~/.ssh
      - run: echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - run: eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa
      - run: ssh-keyscan gvozde0m.beget.tech >> ~/.ssh/known_hosts
      - run: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
      
      # Copy database params
      - run: git clone git@bitbucket.org:redmal/securconfig.git
      - run: cp securconfig/db_params.php app/core/config/
      - run: rm -R securconfig
      
      # Copy files from repository to remote host
      - run: ssh gvozde0m_develop@gvozde0m.beget.tech "rm -R $REPO_NAME -f"
      - run: rsync -av -e ssh --exclude '.gitignore' --exclude '.git' --exclude '.github' $PWD gvozde0m_develop@gvozde0m.beget.tech:~
      
      # Composer and doctrine schemas update
      - run: ssh gvozde0m_develop@gvozde0m.beget.tech "cd $REPO_NAME && composer-php7.3 update"
      - run: ssh gvozde0m_develop@gvozde0m.beget.tech "cd $REPO_NAME && /usr/local/bin/php7.3 vendor/bin/doctrine orm:schema-tool:update --force"        
